# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: url

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # warning: Please pin to latest release (not @main)
      - uses: rzr/url-action@main
        # info: https://github.com/rzr/url-action/releases
        with:
          url: https://github.com/${{ github.repository }}
